### ISSUE TITLE
Cant flip the board

### ISSUE THREAD

**Issue by Teals53** [franciscoBSalgueiro/en-croissant#457] opened 2024-12-09 00:40 UTC
### Describe the bug

title says all

### Reproduction

make black engine and white human and try to flip board it wont working

### Platform and versions

latest

**Comment by the-juju** [comment] 2024-12-11 11:54
I'm not able to reproduce on my side. Woul you like to give more details that can lead to a reproduction?

**Comment by Teals53** [comment] 2024-12-11 12:14
> I'm not able to reproduce on my side. Woul you like to give more details that can lead to a reproduction?

r u related to software?

**Comment by the-juju** [comment] 2024-12-11 12:24
I'm just offering to help. And as I'm not able to reproduce your issue i'm trying to investigate in order to solve your issue.

**Comment by franciscoBSalgueiro** [comment] 2024-12-11 20:10
This was already fixed in the master branch

**Closed by franciscoBSalgueiro** 2024-12-11 20:10 UTC
Labels: type: bug

**Comment by Teals53** [comment] 2024-12-11 20:34
> This was already fixed in the master branch

like we had to wait for release?
