### ISSUE TITLE
Lichess account shows 101% downloaded games.

### ISSUE THREAD

**Issue by Aityz** [franciscoBSalgueiro/en-croissant#286] opened 2024-05-04 03:40 UTC
### Describe the bug

On the Accounts menu in en-croissant, it states that en-croissant has 101.65% of my games downloaded.
<img width="642" alt="image" src="https://github.com/franciscoBSalgueiro/en-croissant/assets/101687337/3db8ae59-02ba-4d6e-b01c-f4be4990d162">

### Reproduction

1. Add a lichess account
2. Let the games download

### Platform and versions

Macbook M1 Air, MacOS 14.3.1.

**Comment by Cankyre** [comment] 2024-05-06 15:10
Duplicate of #84 , explanation of why it can't work in #85 , that's not up to us.

**Closed** 2024-05-09 05:41 UTC
Labels: type: bug
