### ISSUE TITLE
Wrong board orientation in preview board

### ISSUE THREAD

**Issue by yuval59** [franciscoBSalgueiro/en-croissant#158] opened 2024-02-11 14:15 UTC
### Describe the bug

The preview board shown on hover over the engine line does not take into account the live board's orientation - meaning it's always from the white POV
![image](https://github.com/franciscoBSalgueiro/en-croissant/assets/40280822/9f93fba9-ec93-4530-be13-11fa257e1205)

### Reproduction

1. Go to any position
2. Flip the board so you are black
3. Turn on the engine
4. Hover over the suggested line

### Platform and versions

Arch Linux (EndeavourOS Galileo), using the "en-croissant-appimage" package from the AUR

**Comment by franciscoBSalgueiro** [comment] 2024-02-11 14:24
Duplicate of https://github.com/franciscoBSalgueiro/en-croissant/issues/149

**Closed by franciscoBSalgueiro** 2024-02-11 14:24 UTC
Labels: bug

**Comment by yuval59** [comment] 2024-02-11 14:30
To be fair, I do think the 'bug' label is better, but yeah my bad chief
