### ISSUE TITLE
En Croissant Analysis Error

### ISSUE THREAD

**Issue by Ghostdog02** [franciscoBSalgueiro/en-croissant#420] opened 2024-10-21 17:24 UTC
### Describe the bug

When analyzing the below position I get the error illegal position: invalid castling rights

### Reproduction

Position's [FEN "rnbq1rk1/1pp2ppp/4p3/p2nP3/1b1P4/2NB1N2/PP3PPP/R1BQ1RK1 w HQhq - 0 1"]
![image_2024-10-21_202428097](https://github.com/user-attachments/assets/7759931c-4261-4f97-8767-4b906651c795)

### Platform and versions

Version: 0.11.1
Tauri version: 1.6.1
OS: Windows_NT x86_64 10.0.19045
Chess Engine used if matters: Stockfish 17

**Comment by mkyrc** [comment] 2024-11-27 20:00
I hit the same issue. Is there any sokution or workaround?

**Comment by franciscoBSalgueiro** [comment] 2024-12-05 18:49
Duplicate of #346 which has been fixed. The workaround before next version release is to manually fix the casting rights in the FEN (remove HQhq)

**Closed by franciscoBSalgueiro** 2024-12-05 18:49 UTC
Labels: type: bug
