### ISSUE TITLE
113,53% Lichess Data Downloaded

### ISSUE THREAD

**Issue by CaptainTuvok** [franciscoBSalgueiro/en-croissant#203] opened 2024-02-16 21:20 UTC
### Describe the bug

I added my lichess and chess.com Accounts and for the Lichess Account the percentage for the downloaded games is too high 113,53% doesn't seem to be right.
![LichessPercentageBug](https://github.com/franciscoBSalgueiro/en-croissant/assets/111461300/c9f8111b-b1f0-4b64-b774-98a09581135d)

The percentage increases whenever I continue to click on "Download games". The initial value for Chess.com was correct with 100% (as visible in the screenshot) but also increases, whenever I click on "Download games".

### Reproduction

1. Add account
2. Click on download games for either lichess or chess.com Accounts
3. "Downloaded percentage increases"

### Platform and versions

Version: 0.9.2
Tauri version: 1.5.2
OS: Windows_NT x86_64 10.0.19045

**Comment by dav1312** [comment] 2024-02-16 22:18
duplicate of #84

**Closed** 2024-02-17 00:35 UTC
Labels: bug
