### ISSUE TITLE
FEN setup with invalid castling rights when editing

### ISSUE THREAD

**Issue by jez9999** [franciscoBSalgueiro/en-croissant#410] opened 2024-10-10 12:55 UTC
### Describe the bug

When editing the analysis board, the FEN can become invalid for a game of normal chess (possibly it's Chess960 notation?) resulting in the Stockfish engine giving the error "illegal position: invalid castling rights" when turned on.

### Reproduction

1. Open new analysis board
2. Edit mode
3. Move white bishop to F3
4. Move white knight to G3
5. Move white king to G1 (castles)
6. Select "black to move"
7. FEN is now "rnbqkbnr/pppppppp/8/8/8/5BN1/PPPPPPPP/RNBQ1RK1 b HQkq - 0 1", HQkq invalid for regular chess.
8. Analysis | Run, error message from Stockfish.

### Platform and versions

Windows 10, en croissant version 0.11.1

**Comment by franciscoBSalgueiro** [comment] 2024-10-11 15:53
duplicate of #410

**Closed by franciscoBSalgueiro** 2024-10-11 15:53 UTC
Labels: type: bug
